use_frameworks!

platform :ios, '10.0'

target 'GGYYKit_Example' do
  pod 'GGYYKit', :path => '../'

  target 'GGYYKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
